name: CI‑CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build & push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/kushannalinka/ceybank:latest
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.REGISTRY_TOKEN }}

    - name: SSH deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        script: |
          ./CeyBankBankendUsingSpring/scripts/remote-deploy.sh
